#!/bin/bash -x
## SCRIPT PARA PREPARAR GUEST EN MODO VFIO
## FECHA: 9 de mayo de 2023

if [ -z $1 ]; then
	exit 1
fi

function kill_proc(){
	systemctl --user -M 1000@ stop sunshine.service
	lsof -n | grep "$1" | awk '{print $2}' | awk '!seen[$0]++' | xargs -I {} kill -9 {}
	fuser -v "$1" | nl -b n | tail -n 1 | xargs -I {} kill -9 {}
	sleep 2
}

function intel_gpu(){
	cat /sys/class/backlight/intel_backlight/brightness | tee /tmp/brilloPantalla
	systemctl stop display-manager.service
	kill_proc i915
	echo efi-framebuffer.0 | tee /sys/bus/platform/drivers/efi-framebuffer/unbind
        echo 0 | tee /sys/class/vtconsole/vtcon0/bind
        echo 0 | tee /sys/class/vtconsole/vtcon1/bind
	ps -aux | grep Xorg | grep -v grep | awk '{print $2}' | xargs -I {} kill -9 {}
}

VFIO_CONF_DEV_DIR="/usr/local/etc/vfio/devices/$1"

for i in $VFIO_CONF_DEV_DIR/*; do
	source $i
	if [[ "$DRIVER" == "i915" ]]; then
		intel_gpu
		sleep 1
	fi

	if [[ "$DRIVER" == "nvidia" ]]; then
		systemctl stop display-manager.service
		kill_proc /dev/nvidia0
		systemctl stop nvidia-persistenced.service
		killall nvidia-persistenced

if test -e "/tmp/vfio-bound-consoles"; then
    rm -f /tmp/vfio-bound-consoles
fi
for (( i = 0; i < 16; i++))
do
  if test -x /sys/class/vtconsole/vtcon"${i}"; then
      if [ "$(grep -c "frame buffer" /sys/class/vtconsole/vtcon"${i}"/name)" = 1 ]; then
	       echo 0 > /sys/class/vtconsole/vtcon"${i}"/bind
           echo "$DATE Unbinding Console ${i}"
           echo "$i" >> /tmp/vfio-bound-consoles
      fi
  fi
done

#		echo efi-framebuffer.0 | tee /sys/bus/platform/drivers/efi-framebuffer/unbind
#		echo 0 | tee /sys/class/vtconsole/vtcon0/bind
#		echo 0 | tee /sys/class/vtconsole/vtcon1/bind
		modprobe -r nvidia_drm
		modprobe -r nvidia_modeset
		modprobe -r nvidia_uvm
		modprobe -r nvidia
		modprobe -r i2c_nvidia_gpu
		modprobe -r drm_kms_helper
		modprobe -r drm
	fi

	echo "$VENDOR $DEVICE" > "/sys/bus/pci/drivers/vfio-pci/new_id"
	if [ ! -z "$DRIVER" ]; then
		echo "0000:$BUS:$SLOT.$FUNC" > "/sys/bus/pci/drivers/$DRIVER/unbind"
		echo "0000:$BUS:$SLOT.$FUNC" > "/sys/bus/pci/drivers/vfio-pci/bind"
	fi
	sleep 0.25
done
